### ISSUE TITLE
Code is Running since 1-2 hours

### ISSUE THREAD

**Issue by fhashmat** [piergiorgioladisa/KaminskyAttack#1]
Hi,
Your code is running since 1-2 hours on the attacker machine. Can you please guide if this is expected behavior of code?

I have only chnaged the attacker and server IPs as instructed in your readme.

**Comment by piergiorgioladisa** [comment]
> Hi, Your code is running since 1-2 hours on the attacker machine. Can you please guide if this is expected behavior of code?
> 
> I have only chnaged the attacker and server IPs as instructed in your readme.

Hi, 

no, this is not the expected behavior. Actually the code should run pretty fast and succeed in the attack.
Have you checked your network settings and that the two machines are in the same network and they can ping each other?
